.\" This man page is inspired in hello.1 from GNU hello-2.10.
.TH piaq "1" "October 2021" "piaq 1.0" "User Commands"
.SH NAME
piaq - A daemon to serve sensor data to Prometheus queries
.SH SYNOPSIS
.B piaq
.SH DESCRIPTION
Opens a port and serves specified data as key-value pairs
.br
That's it for now
.br
No really
.SH AUTHORS
Joshua Vander Hook, 2021.
